validator:
  name: "validator-3"
  rpc_url: "http://mock-solana:8899?validator=validator-3"
  public_ip_service_urls: ["http://mock-solana:8899/public-ip"]
  identities:
    active: "/tmp/active-identity.json"
    passive: "/tmp/passive-identity-3.json"

cluster:
  name: "mainnet-beta"
  rpc_urls: ["http://mock-cluster:8899"]

prometheus:
  port: 9090
  static_labels:
    environment: "integration-test"
    validator: "validator-3"

failover:
  poll_interval_duration: "3s"
  leaderless_samples_threshold: 3

  self_healthy:
    minimum_duration: "5s"
    poll_interval_duration: "2s"

  active:
    command: "curl"
    args:
      - "-sf"
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "-d"
      - '{"action":"set_active","target":"{{ .SelfName }}"}'
      - "http://mock-solana:8899/action"

  passive:
    command: "curl"
    args:
      - "-sf"
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "-d"
      - '{"action":"set_passive","target":"{{ .SelfName }}"}'
      - "http://mock-solana:8899/action"

  peers:
    validator-1:
      ip: "10.0.0.100"
    validator-2:
      ip: "10.0.0.101"
